# Generated by Django 2.2.3 on 2019-08-28 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=50)),
                ('sundayWork', models.BooleanField(default=False)),
                ('saturdayWork', models.BooleanField(default=False)),
                ('fridayWork', models.BooleanField(default=True)),
                ('thursdayWork', models.BooleanField(default=True)),
                ('wednesdayWork', models.BooleanField(default=True)),
                ('tuesdayWork', models.BooleanField(default=True)),
                ('mondayWork', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_type', models.CharField(choices=[['Private', 'Private Company'], ['Public', 'Public Company']], default='Private', max_length=20)),
                ('company_name', models.CharField(max_length=100)),
                ('company_group', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('holiday', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pjforceCore.Holiday')),
                ('staffs', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
