# Generated by Django 2.1.7 on 2019-02-13 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectcm_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjecRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectrole', models.CharField(choices=[('PM', 'Project Manager'), ('Member', 'Project Member'), ('Stackholder', 'Project Stackholder')], default='Stackholder', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pjname', models.CharField(max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectcm_core.Company')),
            ],
        ),
        migrations.AddField(
            model_name='projecrole',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectcm_core.Project'),
        ),
        migrations.AddField(
            model_name='projecrole',
            name='projectuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
