# Generated by Django 2.1.7 on 2019-02-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectcm_core', '0003_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='actualcompletedate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='actualstartdate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='plannedcompletedate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='plannedstartdate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
