# Generated by Django 2.1.7 on 2019-03-05 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectcm_core', '0006_auto_20190220_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dependencetask',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectcm_core.Task'),
        ),
        migrations.AddField(
            model_name='task',
            name='projecttaskid',
            field=models.IntegerField(default=None, editable=False, null=True),
        ),
    ]
