# Generated by Django 2.1.7 on 2019-03-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectcm_core', '0007_auto_20190306_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='actualresource',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='plannedresource',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True),
        ),
    ]
