# Generated by Django 2.1.7 on 2019-03-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectcm_core', '0008_auto_20190321_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='taskstatus',
            field=models.CharField(choices=[('OPEN', 'Open - Not completed'), ('IN PROGRESS', 'Work In Progress'), ('COMPLETED', 'Completed')], default='OPEN', max_length=20),
        ),
    ]
