# Generated by Django 2.1.7 on 2019-03-30 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectcm_core', '0009_task_taskstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sundayWork', models.BooleanField(default=False)),
                ('saturdayWork', models.BooleanField(default=False)),
                ('fridayWork', models.BooleanField(default=True)),
                ('thursdayWork', models.BooleanField(default=True)),
                ('wednesdayWork', models.BooleanField(default=True)),
                ('tuesdayWork', models.BooleanField(default=True)),
                ('mondayWork', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_date', models.DateField()),
                ('holiday_description', models.CharField(max_length=40)),
                ('holiday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectcm_core.Holiday')),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='taskstatus',
            field=models.CharField(choices=[('OPEN', 'Open - Not completed'), ('INPROGRESS', 'Work In Progress'), ('COMPLETED', 'Completed')], default='OPEN', max_length=20),
        ),
    ]
