# Generated by Django 2.1.7 on 2019-03-30 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectcm_core', '0010_auto_20190330_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='holiday',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectcm_core.Holiday'),
        ),
    ]
