# Generated by Django 2.1.7 on 2019-03-30 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectcm_core', '0011_company_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='name',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
