# Generated by Django 2.1.7 on 2019-03-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectcm_core', '0012_holiday_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[['Private', 'Private Company'], ['Public', 'Public Company']], default='Private', max_length=20),
        ),
    ]
